services:
  skillsharedb:
    image: mariadb
    restart: unless-stopped
    container_name: skillsharedb
    ports:
      - "3315:3306"

    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - skillshare_db:/var/lib/mysql
      - ../database:/docker-entrypoint-initdb.d
    networks:
      - skillshare_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: shareskill_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=skillsharedb
      - PMA_PORT=${PMA_PORT}
    depends_on:
      - skillsharedb
    networks:
      - skillshare_network

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - ${MAILPIT_HTTP_PORT}:8025
      - ${MAILPIT_SMTP_PORT}:1025

volumes:
  skillshare_db:

networks:
  skillshare_network:
    external: true
    name: skillshare_network
